name: teachr
description: Teachr, de app voor hybride-docenten!
homepage: www.teachrapp.nl

version: 1.0.0+3

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: ^0.12.0+1
  flutter:
    sdk: flutter
  # flutter_crashlytics: ^1.0.0
  transparent_image: ^0.1.0
  cached_network_image: 2.0.0-rc
  auto_size_text: ^1.0.0
  google_maps_flutter: ^0.3.0+2
  flutter_html: ^0.9.4
  url_launcher: ^5.0.1
  intl: 0.16.1
  dio: ^2.1.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.9.13+1
  flutter_slidable: ^0.4.9
  firebase_auth: ^0.8.4+3
  intro_slider: ^1.2.0
  flutter_secure_storage: ^3.2.1+1 
  shared_preferences: ^0.5.2
  google_sign_in: ^4.0.1+3
  flutter_typeahead: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1
  font_awesome_flutter: ^8.0.1

flutter:
  uses-material-design: true

  assets:
  - assets/img/
  - assets/lang/nl.json
  - assets/lang/en.json

  fonts:
  - family: Roboto
    fonts:
    - asset: assets/fonts/Roboto/Roboto-Regular.ttf

  - family: Nunito
    fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 900

  - family: RedHatDisplay
    fonts:
      - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-Italic.ttf

  - family: ReneBieder
    fonts:
      - asset: assets/fonts/Choplin/Rene Bieder - Choplin Bold Italic.otf
